### ISSUE TITLE
zig build fails (Zig compiler version?)

### ISSUE THREAD

**Issue by bortzmeyer** [Remy2701/zigplotlib#1]
I do not find where is documented the compiler version to use. With 0.12.0-dev.1245+a07f288eb:

```
% zig build
zig build-exe zigplotlib Debug native: error: the following command failed with 6 compilation errors:
/usr/local/zig/zig-linux-x86_64-0.12.0-dev.1245+a07f288eb/zig build-exe /home/stephane/tmp/zigplotlib/src/main.zig --cache-dir /home/stephane/tmp/zigplotlib/zig-cache --global-cache-dir /home/stephane/.cache/zig --name zigplotlib --listen=- 
Build Summary: 2/5 steps succeeded; 1 failed (disable with --summary none)
install transitive failure
└─ install zigplotlib transitive failure
   └─ zig build-exe zigplotlib Debug native 6 errors
src/plot/Area.zig:38:28: error: no field named '0' in struct 'mem.minMax__struct_7927'
            .min = min_max.@"0",
                           ^~~~
/usr/local/zig/zig-linux-x86_64-0.12.0-dev.1245+a07f288eb/lib/std/mem.zig:3541:51: note: struct declared here
pub fn minMax(comptime T: type, slice: []const T) struct { min: T, max: T } {
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
    interface: src/plot/Area.zig:124:10
    addPlot__anon_4475: src/plot/Figure.zig:137:34
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
src/plot/Area.zig:54:24: error: no field named '0' in struct 'mem.minMax__struct_7929'
        .min = min_max.@"0",
                       ^~~~
/usr/local/zig/zig-linux-x86_64-0.12.0-dev.1245+a07f288eb/lib/std/mem.zig:3541:51: note: struct declared here
pub fn minMax(comptime T: type, slice: []const T) struct { min: T, max: T } {
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~
src/plot/Scatter.zig:53:28: error: no field named '0' in struct 'mem.minMax__struct_7993'
            .min = min_max.@"0",
                           ^~~~
/usr/local/zig/zig-linux-x86_64-0.12.0-dev.1245+a07f288eb/lib/std/mem.zig:3541:51: note: struct declared here
pub fn minMax(comptime T: type, slice: []const T) struct { min: T, max: T } {
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~
src/plot/Scatter.zig:69:24: error: no field named '0' in struct 'mem.minMax__struct_7995'
        .min = min_max.@"0",
                       ^~~~
/usr/local/zig/zig-linux-x86_64-0.12.0-dev.1245+a07f288eb/lib/std/mem.zig:3541:51: note: struct declared here
pub fn minMax(comptime T: type, slice: []const T) struct { min: T, max: T } {
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~
src/plot/Line.zig:36:28: error: no field named '0' in struct 'mem.minMax__struct_8005'
            .min = min_max.@"0",
                           ^~~~
/usr/local/zig/zig-linux-x86_64-0.12.0-dev.1245+a07f288eb/lib/std/mem.zig:3541:51: note: struct declared here
pub fn minMax(comptime T: type, slice: []const T) struct { min: T, max: T } {
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~
src/plot/Line.zig:52:24: error: no field named '0' in struct 'mem.minMax__struct_8007'
        .min = min_max.@"0",
                       ^~~~
/usr/local/zig/zig-linux-x86_64-0.12.0-dev.1245+a07f288eb/lib/std/mem.zig:3541:51: note: struct declared here
pub fn minMax(comptime T: type, slice: []const T) struct { min: T, max: T } {
                                          
```

**Comment by Remy2701** [comment]
Oh right, I'm working with version 0.12.0-dev.1768+39a966b0a
I see the `minMax` function has been changed between those two versions, thanks for the notice, I'll update the readme
